os: osx
language: objective-c
osx_image: xcode8.3
xcode_workspace: Careo.xcodeworkspace
xcode_scheme: Careo
script: xcodebuild clean build test -workspace Careo.xcworkspace -scheme Careo -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' ONLY_ACTIVE_ARCH=NO | xcpretty
